# @name Users API Endpoints

@baseUrl = http://localhost:3000/api/v1

### Create a new user
// Expected HTTP response status code: 201
// Expected response: a user object (json)
# @name createUser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "test83@example.com",
    "password": "password123",
    "role": "participant"
}

###

@userId = {{createUser.response.body._id}}
@userEmail = {{createUser.response.body.email}}

###

### Update the created user by email
// Expected HTTP response status code: 200
# @name updateUserByEmail
PUT {{baseUrl}}/users/email/{{userEmail}}
Content-Type: application/json

{
    "email": "updatedUsingEmail@example.com"
}

### Update the created user by id
// Expected HTTP response status code: 200
# @name updateUserById
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
    "email": "updatedUsingId@example.com"
}

### Get specific user by ID
// Test: Get specific user
// Expected HTTP response status code: 200
// Expected response: a user object (json)
GET {{baseUrl}}/users/{{userId}}

### Create a new user to add as shared contact
// Expected HTTP response status code: 201
// Expected response: a user object (json)
# @name createSharedContactUser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "sharedContact@example.com",
    "password": "password123",
    "role": "participant"
}

###

@sharedContactId = {{createSharedContactUser.response.body._id}}

### Add a shared contact
// Expected HTTP response status code: 201
// Expected response: created shared contact object
# @name addSharedContact
POST {{baseUrl}}/users/{{userId}}/shared-contacts
Content-Type: application/json

{
    "contactId": "{{sharedContactId}}"
}

###

@addedContactId = {{addSharedContact.response.body.contact}}

### Create a third user to add as another shared contact
// Expected HTTP response status code: 201
// Expected response: a user object (json)
# @name createSecondSharedContactUser
POST {{baseUrl}}/users
Content-Type: application/json

{
    "email": "sharedContact2@example.com",
    "password": "password123",
    "role": "participant"
}

###

@secondSharedContactId = {{createSecondSharedContactUser.response.body._id}}


### Add the second shared contact
// Expected HTTP response status code: 201
// Expected response: created shared contact object
# @name addSecondSharedContact
POST {{baseUrl}}/users/{{userId}}/shared-contacts
Content-Type: application/json

{
    "contactId": "{{secondSharedContactId}}"
}

### Get all shared contacts for a user
// Expected HTTP response status code: 200
// Expected response: array of shared contacts
GET {{baseUrl}}/users/{{userId}}/shared-contacts

###

### Get a specific shared contact
// Expected HTTP response status code: 200
// Expected response: shared contact object
GET {{baseUrl}}/users/{{userId}}/shared-contacts/{{sharedContactId}}

### Update a shared contact
// Expected HTTP response status code: 200
// Expected response: updated shared contact object
PUT {{baseUrl}}/users/{{userId}}/shared-contacts/{{sharedContactId}}
Content-Type: application/json

{
    "status": "accepted"
}

### Get all users
// Test: Get all users
// Expected HTTP response status code: 200
// Expected response: an array (json) with all users
GET {{baseUrl}}/users

### Remove a shared contact
// Expected HTTP response status code: 200
DELETE {{baseUrl}}/users/{{userId}}/shared-contacts/{{sharedContactId}}

### Remove a not existing shared contact
// Expected HTTP response status code: 404
DELETE {{baseUrl}}/users/{{userId}}/shared-contacts/67b0a9bec6f8a15f513ed713


### Delete the user
// Expected HTTP response status code: 200
DELETE {{baseUrl}}/users/{{userId}}

### Delete the shared contact user
// Expected HTTP response status code: 200
DELETE {{baseUrl}}/users/{{sharedContactId}}

### Delete the second shared contact user
// Expected HTTP response status code: 200
DELETE {{baseUrl}}/users/{{secondSharedContactId}}
